#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot brightness; do
	alias $command="sudo $command"
done; unset command

mkd() { mkdir -pv "$@" && cd "$@"; }
exn() { [[ -t 1 ]] && echo "$@" || notify-send -- "$@" }
dxf() {	[[ -t 1 ]] && shift && fzf $@ || dmenu -i -l 30 -p $@ }
am() { cd "$(android-mount)" }
rmo() { rmn "$@" }
cpstat() { time rsync -a --info=progress2 --stats $1 $2 }
se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}
lg() {
	git rev-parse 2>/dev/null;
	[ ! $? = 0 ] && cd $REPOSITORIES/voidrice
	lazygit
	;}

# Verbosity and settings that you pretty much just always are going to want.
#rm="rm -vI" \
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rmo" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	yts="ytd --write-subs --sub-langs 'en,de'" \
	yta3="yta --audio-format mp3" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lahN --color=auto --group-directories-first" \
	ltr="ls -ltr --color=auto --group-directories-first"
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	gu="git ls-files --other --exclude-standard --directory ." \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xxq="xbps-query" \
	x="xdg-open"

alias \
	z="zathura" \
	pbcopy="xclip -selection c" \
	pbpaste="xclip -selection clipboard -o" \
	unsorted="note --unsorted" \
	daily="note --daily" \
	mp="ncmpc --host=127.0.0.1 --port=6600" \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
	ld="lazydocker" \
	snippets="vim $HOME/.local/share/larbs/snippets"
