#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot brightness; do
	alias $command="sudo $command"
done; unset command

mkd() { mkdir -pv "$@" && cd "$@"; }
nv() { cd "$(nova-air)" }
rmo() { rmn "$@" }
cpstat() { time rsync -a --info=progress2 --stats $1 $2 }

# Verbosity and settings that you pretty much just always are going to want.
#rm="rm -vI" \
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rmo" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="ytd --embed-metadata -i" \
	yts="ytd --write-subs --sub-langs 'en,de'" \
	yta="yt -x -f bestaudio/best" \
	yta3="yta --audio-format mp3" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lahN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	gu="git ls-files --other --exclude-standard --directory ." \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xxq="xbps-query" \
	x="xdg-open"

alias \
	z="zathura" \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	pbcopy="xclip -selection c" \
	pbpaste="xclip -selection clipboard -o" \
	unsorted="note --unsorted" \
	daily="note --daily" \
	mp="ncmpc --host=127.0.0.1 --port=6600"

